In [1]:
import pandas as pd

In [2]:
pd.read_csv("netflix.csv")

                      title        director date_added     type
0               Alias Grace             NaN   3-Nov-17  TV Show
1            A Patch of Fog  Michael Lennox  15-Apr-17    Movie
2                  Lunatics             NaN  19-Apr-19  TV Show
3                 Uriyadi 2     Vijay Kumar   2-Aug-19    Movie
4         Shrek the Musical     Jason Moore  29-Dec-13    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola   7-Aug-19    Movie
5833       Hurricane Bianca   Matt Kugelman   1-Jan-17    Movie
5834           Amar's Hands  Khaled Youssef  26-Apr-19    Movie
5835  Bill Nye: Science Guy  Jason Sussberg  25-Apr-18    Movie
5836           Age of Glory             NaN        NaN  TV Show

[5837 rows x 4 columns]

In [28]:
netflix = pd.read_csv('netflix.csv')

In [7]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   object
 3   type        5837 non-null   object
dtypes: object(4)
memory usage: 182.5+ KB

In [9]:
#1 Optimize the data set for limited memory use and maximum utility.
netflix['date_added'] = netflix['date_added'].astype('datetime64[ns]')

In [10]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 182.5+ KB

In [20]:
netflix.nunique()

title         5780
director      3024
date_added    1092
type             2
dtype: int64

In [12]:
netflix['type'] = netflix['type'].astype('category')

In [13]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

In [21]:
#2 Find all rows with a title of `"Limitless"`.
type(netflix['title'] == 'Limitless')

pandas.core.series.Series

In [22]:
netflix['title'] == 'Limitless'

0       False
1       False
2       False
3       False
4       False
        ...
5832    False
5833    False
5834    False
5835    False
5836    False
Name: title, Length: 5837, dtype: bool

In [71]:
netflix[netflix['title'] == 'Limitless']

          title         director date_added     type
1559  Limitless      Neil Burger  16-May-19    Movie
2564  Limitless              NaN   1-Jul-16  TV Show
4579  Limitless  Vrinda Samartha   1-Oct-19    Movie

In [ ]:
#Whats the difference between these two?

In [73]:
######
directed_by_robert_rodriguez = (
    netflix["director"] == "Robert Rodriguez"
)
is_movie = netflix["type"] == "Movie"

netflix[directed_by_robert_rodriguez & is_movie]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,19-Feb-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,1-Apr-19,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,8-Mar-19,Movie
2890,Sin City,Robert Rodriguez,1-Oct-19,Movie
3836,Shorts,Robert Rodriguez,1-Jul-19,Movie
3883,Spy Kids,Robert Rodriguez,1-Apr-19,Movie

In [76]:
#4 Find all rows with either a date_added of `"2019-07-31"`
####or a director of `"Robert Altman"`.
added_on_july_31[netflix['date_added'] == '2019-07-31'] 
netflix[netflix['director'] == 'Robert Altman']

      title  director  date_added   type
611   False     False       False  False
1092  False     False       False  False

In [46]:
#5 Find all rows with a director of `"Orson Welles"`, `"Aditya Kripalani"`, or `"Sam Raimi"`.
netflix[netflix['director'] == 'Orson Welles']
netflix[netflix['director'] == 'Aditya Kripalani']
netflix[netflix['director'] == 'Sam Raini']

Empty DataFrame
Columns: [title, director, date_added, type]
Index: []

In [59]:
#6 Find all rows with a date_added value 
####between May 1, 2019 and June 1, 2019.
netflix[netflix['date_added'] <= '2019-05-01']
netflix[netflix['date_added'] >= '2019-06-01']

,title,director,date_added,type
0,Alias Grace,NaN,3-Nov-17,TV Show
4,Shrek the Musical,Jason Moore,29-Dec-13,Movie
7,7SEEDS,NaN,28-Jun-19,TV Show
9,You,Lee Toland Krieger,26-Dec-18,TV Show
12,Without Gorky,Cosima Spender,31-May-17,Movie
...,...,...,...,...
5827,Struggle: The Life and Lost Art of Szukalski,Irek Dobrowolski,21-Dec-18,Movie
5828,Saavat,Saurabh Sinha,23-Aug-19,Movie
5832,The Pursuit,John Papola,7-Aug-19,Movie
5834,Amar's Hands,Khaled Youssef,26-Apr-19,Movie
5835,Bill Nye: Science Guy,Jason Sussberg,25-Apr-18,Movie

In [61]:
netflix

                      title        director date_added     type
0               Alias Grace             NaN   3-Nov-17  TV Show
1            A Patch of Fog  Michael Lennox  15-Apr-17    Movie
2                  Lunatics             NaN  19-Apr-19  TV Show
3                 Uriyadi 2     Vijay Kumar   2-Aug-19    Movie
4         Shrek the Musical     Jason Moore  29-Dec-13    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola   7-Aug-19    Movie
5833       Hurricane Bianca   Matt Kugelman   1-Jan-17    Movie
5834           Amar's Hands  Khaled Youssef  26-Apr-19    Movie
5835  Bill Nye: Science Guy  Jason Sussberg  25-Apr-18    Movie
5836           Age of Glory             NaN        NaN  TV Show

[5837 rows x 4 columns]

In [60]:
#Drop all rows with a NaN value in the director column.
netflix.dropna()

                                   title        director date_added   type
1                         A Patch of Fog  Michael Lennox  15-Apr-17  Movie
3                              Uriyadi 2     Vijay Kumar   2-Aug-19  Movie
4                      Shrek the Musical     Jason Moore  29-Dec-13  Movie
5                       Schubert In Love     Lars Büchel   1-Mar-18  Movie
6     We Have Always Lived in the Castle   Stacie Passon  14-Sep-19  Movie
...                                  ...             ...        ...    ...
5830                         Bibi & Tina     Detlev Buck  15-Apr-17  Movie
5832                         The Pursuit     John Papola   7-Aug-19  Movie
5833                    Hurricane Bianca   Matt Kugelman   1-Jan-17  Movie
5834                        Amar's Hands  Khaled Youssef  26-Apr-19  Movie
5835               Bill Nye: Science Guy  Jason Sussberg  25-Apr-18  Movie

[3901 rows x 4 columns]

In [ ]:
#8 Identify the days when Netflix added only one movie to its catalog.